# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VerticalLayoutFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	inhibit_all_warnings!
  
  pod 'RxSwift', '5.0.0'
  pod 'RxCocoa', '5.0.0'
  pod 'RxGesture', '3.0.1'
  pod 'SnapKit', '4.2.0'
  pod 'Kingfisher', '4.10.1' #图片加载
  # Pods for VerticalLayoutFramework

  target 'VerticalLayoutFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VerticalLayoutFrameworkUITests' do
    # Pods for testing
  end

end
